### ISSUE TITLE
Error: Muse provide a url

### ISSUE THREAD

**Issue by 3l0w** [diyews/m3u8-merger#1]
`m3u8Merger.m3u8Merger(url,"twitch",false,"ts")`
with this code i got Muse provide a url

**Comment by diyews** [comment]
> `m3u8Merger.m3u8Merger(url,"twitch",false,"ts")`

Sorry I forgot to watch this repo.
Try the named parameters like below

`m3u8Merger.m3u8Merger({url, dir: "twitch", isConvert: false, format: "ts"})`

**Comment by 3l0w** [comment]
thanks for responce
